apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/managed-by: kustomize
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
  size: 3                   # 符合 1 <= size <= 10 的规则
  configMapName: my-config  # 符合 1 <= 长度 <= 15 的规则
  alias: Phone              # 必须是 Phone、Address 或 Name 之一
